    name: Deploy infrastructure

    on: 
      push:
        branches:
            - main
    permissions:
        id-token: write
        contents: read
    jobs:
        build-and-deploy:
            name: Deploy site
            runs-on: ubuntu-latest
            env:
                ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform fmt
              id: fmt
              run: terraform fmt 
              continue-on-error: true
              working-directory: Infrastructure
            
            - name: Terraform Init
              id: init
              run: terraform init
              working-directory: Infrastructure
            
            - name: Terraform Validate
              id: validate
              run: terraform validate
              working-directory: Infrastructure
            
            - name: Terraform Apply
              id: apply
              run: terraform apply -auto-approve
              working-directory: Infrastructure
            
            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az storage blob upload-batch \
                    --destination \$web$web/frontend \
                    --source "/home/runner/work/CloudResumeChallenge/CloudResumeChallenge/frontend" \
                    --account-name ydsunstorageaccount \
                    --overwrite true \
                    --account-key ${{ secrets.ARM_ACCESS_KEY }} \
                  
              
                    az storage blob upload-batch \
                    --account-name ydsunstorageaccount \
                    --source "/home/runner/work/CloudResumeChallenge/CloudResumeChallenge/resume" \
                    --destination \$web/resume \
                    --overwrite true \
                    --account-key ${{ secrets.ARM_ACCESS_KEY }} 
      
     

            
           
              


                






